In [47]:
import pandas as pd

In [48]:
nrows = 1000

In [49]:
df = pd.read_csv(r"D:\subtitles.csv",nrows = nrows)

In [50]:
df.head()

,Unnamed: 0,num,name,content,file_content,clean_text_lemma,text_length_lemma
0,0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",watch any video online with open subtitle free...,9198
1,1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther...",ah there s princess dawn and terry with the bl...,927
2,2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'...",yumi s cell episode extremely polite yumi yumi...,5339
3,3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",watch any video online with open subtitle free...,5930
4,4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch...",watch any video online with open subtitle free...,10135

In [51]:
df.drop(["Unnamed: 0"],axis = 1,inplace = True)

In [59]:
df.head()

,num,file_name,content,file_content,clean_text_lemma,text_length_lemma,aa,aaaa,aaaaaaah,aaaaaah,...,zumba,zur,zurich,zurrell,zuruckkommen,zutto,zwei,zzing,zzt,zzzz
0,9180533,the.message.(1976).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x1c\xa9\x...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",watch any video online with open subtitle free...,9198,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,9180583,here.comes.the.grump.s01.e09.joltin.jack.in.bo...,b'PK\x03\x04\x14\x00\x00\x00\x08\x00\x17\xb9\x...,"1\r\n00:00:29,359 --> 00:00:32,048\r\nAh! Ther...",ah there s princess dawn and terry with the bl...,927,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,9180592,yumis.cells.s02.e13.episode.2.13.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00L\xb9\x99V...,"1\r\n00:00:53,200 --> 00:00:56,030\r\n<i>Yumi'...",yumi s cell episode extremely polite yumi yumi...,5339,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,9180594,yumis.cells.s02.e14.episode.2.14.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x00U\xa9\x99V...,"1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch an...",watch any video online with open subtitle free...,5930,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,9180600,broker.(2022).eng.1cd,b'PK\x03\x04\x14\x00\x00\x00\x08\x001\xa9\x99V...,"ï»¿1\r\n00:00:06,000 --> 00:00:12,074\r\nWatch...",watch any video online with open subtitle free...,10135,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
df.clean_text_lemma.isnull().sum()

0

In [61]:
df.rename({"name": "file_name" }, inplace=True, axis=1)

In [62]:

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(df.clean_text_lemma)

In [63]:
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

# Concatenate the original DataFrame with the TF-IDF DataFrame
df = pd.concat([df, tfidf_df], axis=1)

In [64]:
from sklearn.metrics.pairwise import cosine_similarity

In [68]:
def find_similar_records(query, df, tfidf_vectorizer, tfidf_matrix):
    query_vector = tfidf_vectorizer.transform([query])
    cosine_similarities = cosine_similarity(query_vector, tfidf_matrix).flatten()
    similar_records_indices = cosine_similarities.argsort()[::-1]
    similar_records = df.iloc[similar_records_indices]
    return similar_records

In [69]:
# Assuming imports are done earlier in the code
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Assuming tfidf_vectorizer and tfidf_matrix are already created
query = input('Search : ')
similar_records = find_similar_records(query, df, tfidf_vectorizer, tfidf_matrix)

# Display the top N similar records
top_n = int(input('Enter the No.of Search Results you want :'))
top_similar_records = similar_records.head(top_n)
print(f"Top {top_n} similar records for query '{query}':")
print(top_similar_records[['file_name', 'similarity']])

Search : video
Enter the No.of Search Results you want :5
Top 5 similar records for query 'video':
                                             file_name  file_name  similarity  \
937  keep.breathing.s01.e05.awake.dreaming.(2022).e...   0.000000         0.0
936   keep.breathing.s01.e04.departures.(2022).eng.1cd   0.000000         0.0
969    another.self.s01.e08.episode.1.8.(2022).eng.1cd   0.000000         0.0
90   reetur.s01.e04.the.second.time.will.be.easier....   0.005495         0.0
981  pretty.little.liars.original.sin.s01.e02.chapt...   0.002580         0.0

     similarity
937         0.0
936         0.0
969         0.0
90          0.0
981         0.0